### ISSUE TITLE
Node 4 compatibility

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/imocha#18]
Prompted by #14. It occurred to me that mocha has commander locked to version 2.15.1 because that is the newest that did not drop node v4 support yet.

If we want to follow mocha's lead in this case, now would be a good time to pivot away from async/await :-)

**Comment by papandreou** [comment]
It's fair enough that the test runner itself supports older node versions for CI etc., but I can certainly live with the interactive mode not doing so.

**Comment by gustavnikolaj** [comment]
Right, that's a good point. Nothing's preventing you from running older node versions on CI as long as you don't execute `imocha`.

Or... I suppose I need to remove the `engine` property from package.json and move the version checking into the binary or `src/cli.js` instead. `yarn` will complain if you try to install it on a version of node that does not satisfy the requirement.

**Comment by alexjeffburke** [comment]
I think I lean towards @papandreou here too. Also, might be worth checking with the `mocha` folks on how long they intend to keep node 4 support alive given it is now officially EoL. My guess is one of their constraints is actually their browser support.

**Comment by gustavnikolaj** [comment]
I think we need to stick with locking commander down to the same version as mocha though - that reduces the risk of the option parsing diverging between the two and keeps imocha from preventing people to install their dependencies on older versions of node.

**Comment by gustavnikolaj** [comment]
I'm reopening this issue - I think we need to remove the engine field in package json and add version detection to javascript instead before we can close it :-)

**Comment by gustavnikolaj** [comment]
We are using async await and that mandates 8.3.0+. So that'll at least have to change before, and we have recently started using mocha@^6 which to my knowledge also dropped node 4 support at the same time. So for now I'll close this issue and wait for complaints before we address anything :-)
